#数据库配置信息
mysql:
  Host : 127.0.0.1
  Port: 3306
  User: root
  PassWord: xtc
  DataBase: tiktok
  CharSet: utf8mb4
  ParseTime: True
  Loc: Local

#redis配置信息
redis:
  IP:       8.134.108.219
  Port:     6379
  PassWord: XTCqq+582
  DataBase: 0


#服务器服务端口
server:
  IP:  192.168.1.187
  Port: 8080
#资源路径
path:
  StaticPath: ./static